# CMake generated Testfile for 
# Source directory: /home/leah/catkin_ws/src/gtsam/gtsam/symbolic/tests
# Build directory: /home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/symbolic/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(testSerializationSymbolic "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/symbolic/tests/testSerializationSymbolic")
set_tests_properties(testSerializationSymbolic PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/symbolic/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/symbolic/tests/CMakeLists.txt;0;")
add_test(testSymbolicBayesNet "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/symbolic/tests/testSymbolicBayesNet")
set_tests_properties(testSymbolicBayesNet PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/symbolic/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/symbolic/tests/CMakeLists.txt;0;")
add_test(testSymbolicBayesTree "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/symbolic/tests/testSymbolicBayesTree")
set_tests_properties(testSymbolicBayesTree PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/symbolic/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/symbolic/tests/CMakeLists.txt;0;")
add_test(testSymbolicConditional "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/symbolic/tests/testSymbolicConditional")
set_tests_properties(testSymbolicConditional PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/symbolic/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/symbolic/tests/CMakeLists.txt;0;")
add_test(testSymbolicEliminationTree "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/symbolic/tests/testSymbolicEliminationTree")
set_tests_properties(testSymbolicEliminationTree PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/symbolic/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/symbolic/tests/CMakeLists.txt;0;")
add_test(testSymbolicFactor "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/symbolic/tests/testSymbolicFactor")
set_tests_properties(testSymbolicFactor PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/symbolic/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/symbolic/tests/CMakeLists.txt;0;")
add_test(testSymbolicFactorGraph "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/symbolic/tests/testSymbolicFactorGraph")
set_tests_properties(testSymbolicFactorGraph PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/symbolic/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/symbolic/tests/CMakeLists.txt;0;")
add_test(testSymbolicISAM "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/symbolic/tests/testSymbolicISAM")
set_tests_properties(testSymbolicISAM PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/symbolic/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/symbolic/tests/CMakeLists.txt;0;")
add_test(testSymbolicJunctionTree "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/symbolic/tests/testSymbolicJunctionTree")
set_tests_properties(testSymbolicJunctionTree PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/symbolic/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/symbolic/tests/CMakeLists.txt;0;")
add_test(testVariableIndex "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/symbolic/tests/testVariableIndex")
set_tests_properties(testVariableIndex PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/symbolic/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/symbolic/tests/CMakeLists.txt;0;")
