# CMake generated Testfile for 
# Source directory: /home/leah/catkin_ws/src/gtsam/gtsam/nonlinear/tests
# Build directory: /home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/nonlinear/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(testAdaptAutoDiff "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/nonlinear/tests/testAdaptAutoDiff")
set_tests_properties(testAdaptAutoDiff PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/nonlinear/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/nonlinear/tests/CMakeLists.txt;0;")
add_test(testCallRecord "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/nonlinear/tests/testCallRecord")
set_tests_properties(testCallRecord PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/nonlinear/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/nonlinear/tests/CMakeLists.txt;0;")
add_test(testExecutionTrace "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/nonlinear/tests/testExecutionTrace")
set_tests_properties(testExecutionTrace PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/nonlinear/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/nonlinear/tests/CMakeLists.txt;0;")
add_test(testExpression "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/nonlinear/tests/testExpression")
set_tests_properties(testExpression PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/nonlinear/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/nonlinear/tests/CMakeLists.txt;0;")
add_test(testFactorTesting "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/nonlinear/tests/testFactorTesting")
set_tests_properties(testFactorTesting PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/nonlinear/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/nonlinear/tests/CMakeLists.txt;0;")
add_test(testFunctorizedFactor "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/nonlinear/tests/testFunctorizedFactor")
set_tests_properties(testFunctorizedFactor PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/nonlinear/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/nonlinear/tests/CMakeLists.txt;0;")
add_test(testLinearContainerFactor "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/nonlinear/tests/testLinearContainerFactor")
set_tests_properties(testLinearContainerFactor PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/nonlinear/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/nonlinear/tests/CMakeLists.txt;0;")
add_test(testSerializationNonlinear "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/nonlinear/tests/testSerializationNonlinear")
set_tests_properties(testSerializationNonlinear PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/nonlinear/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/nonlinear/tests/CMakeLists.txt;0;")
add_test(testUtilities "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/nonlinear/tests/testUtilities")
set_tests_properties(testUtilities PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/nonlinear/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/nonlinear/tests/CMakeLists.txt;0;")
add_test(testValues "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/nonlinear/tests/testValues")
set_tests_properties(testValues PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/nonlinear/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/nonlinear/tests/CMakeLists.txt;0;")
add_test(testWhiteNoiseFactor "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/nonlinear/tests/testWhiteNoiseFactor")
set_tests_properties(testWhiteNoiseFactor PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/nonlinear/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/nonlinear/tests/CMakeLists.txt;0;")
