# CMake generated Testfile for 
# Source directory: /home/leah/catkin_ws/src/gtsam/gtsam/hybrid/tests
# Build directory: /home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/hybrid/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(testGaussianMixture "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/hybrid/tests/testGaussianMixture")
set_tests_properties(testGaussianMixture PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/hybrid/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/hybrid/tests/CMakeLists.txt;0;")
add_test(testGaussianMixtureFactor "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/hybrid/tests/testGaussianMixtureFactor")
set_tests_properties(testGaussianMixtureFactor PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/hybrid/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/hybrid/tests/CMakeLists.txt;0;")
add_test(testHybridBayesNet "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/hybrid/tests/testHybridBayesNet")
set_tests_properties(testHybridBayesNet PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/hybrid/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/hybrid/tests/CMakeLists.txt;0;")
add_test(testHybridBayesTree "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/hybrid/tests/testHybridBayesTree")
set_tests_properties(testHybridBayesTree PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/hybrid/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/hybrid/tests/CMakeLists.txt;0;")
add_test(testHybridConditional "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/hybrid/tests/testHybridConditional")
set_tests_properties(testHybridConditional PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/hybrid/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/hybrid/tests/CMakeLists.txt;0;")
add_test(testHybridEstimation "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/hybrid/tests/testHybridEstimation")
set_tests_properties(testHybridEstimation PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/hybrid/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/hybrid/tests/CMakeLists.txt;0;")
add_test(testHybridFactorGraph "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/hybrid/tests/testHybridFactorGraph")
set_tests_properties(testHybridFactorGraph PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/hybrid/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/hybrid/tests/CMakeLists.txt;0;")
add_test(testHybridGaussianFactorGraph "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/hybrid/tests/testHybridGaussianFactorGraph")
set_tests_properties(testHybridGaussianFactorGraph PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/hybrid/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/hybrid/tests/CMakeLists.txt;0;")
add_test(testHybridGaussianISAM "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/hybrid/tests/testHybridGaussianISAM")
set_tests_properties(testHybridGaussianISAM PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/hybrid/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/hybrid/tests/CMakeLists.txt;0;")
add_test(testHybridNonlinearFactorGraph "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/hybrid/tests/testHybridNonlinearFactorGraph")
set_tests_properties(testHybridNonlinearFactorGraph PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/hybrid/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/hybrid/tests/CMakeLists.txt;0;")
add_test(testHybridNonlinearISAM "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/hybrid/tests/testHybridNonlinearISAM")
set_tests_properties(testHybridNonlinearISAM PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/hybrid/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/hybrid/tests/CMakeLists.txt;0;")
add_test(testHybridValues "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/hybrid/tests/testHybridValues")
set_tests_properties(testHybridValues PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/hybrid/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/hybrid/tests/CMakeLists.txt;0;")
add_test(testMixtureFactor "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/hybrid/tests/testMixtureFactor")
set_tests_properties(testMixtureFactor PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/hybrid/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/hybrid/tests/CMakeLists.txt;0;")
add_test(testSerializationHybrid "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/hybrid/tests/testSerializationHybrid")
set_tests_properties(testSerializationHybrid PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/hybrid/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/hybrid/tests/CMakeLists.txt;0;")
