# CMake generated Testfile for 
# Source directory: /home/leah/catkin_ws/src/gtsam/gtsam/discrete/tests
# Build directory: /home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/discrete/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(testAlgebraicDecisionTree "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/discrete/tests/testAlgebraicDecisionTree")
set_tests_properties(testAlgebraicDecisionTree PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/discrete/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/discrete/tests/CMakeLists.txt;0;")
add_test(testDecisionTree "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/discrete/tests/testDecisionTree")
set_tests_properties(testDecisionTree PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/discrete/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/discrete/tests/CMakeLists.txt;0;")
add_test(testDecisionTreeFactor "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/discrete/tests/testDecisionTreeFactor")
set_tests_properties(testDecisionTreeFactor PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/discrete/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/discrete/tests/CMakeLists.txt;0;")
add_test(testDiscreteBayesNet "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/discrete/tests/testDiscreteBayesNet")
set_tests_properties(testDiscreteBayesNet PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/discrete/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/discrete/tests/CMakeLists.txt;0;")
add_test(testDiscreteBayesTree "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/discrete/tests/testDiscreteBayesTree")
set_tests_properties(testDiscreteBayesTree PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/discrete/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/discrete/tests/CMakeLists.txt;0;")
add_test(testDiscreteConditional "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/discrete/tests/testDiscreteConditional")
set_tests_properties(testDiscreteConditional PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/discrete/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/discrete/tests/CMakeLists.txt;0;")
add_test(testDiscreteDistribution "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/discrete/tests/testDiscreteDistribution")
set_tests_properties(testDiscreteDistribution PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/discrete/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/discrete/tests/CMakeLists.txt;0;")
add_test(testDiscreteFactor "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/discrete/tests/testDiscreteFactor")
set_tests_properties(testDiscreteFactor PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/discrete/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/discrete/tests/CMakeLists.txt;0;")
add_test(testDiscreteFactorGraph "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/discrete/tests/testDiscreteFactorGraph")
set_tests_properties(testDiscreteFactorGraph PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/discrete/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/discrete/tests/CMakeLists.txt;0;")
add_test(testDiscreteLookupDAG "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/discrete/tests/testDiscreteLookupDAG")
set_tests_properties(testDiscreteLookupDAG PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/discrete/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/discrete/tests/CMakeLists.txt;0;")
add_test(testDiscreteMarginals "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/discrete/tests/testDiscreteMarginals")
set_tests_properties(testDiscreteMarginals PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/discrete/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/discrete/tests/CMakeLists.txt;0;")
add_test(testDiscreteValues "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/discrete/tests/testDiscreteValues")
set_tests_properties(testDiscreteValues PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/discrete/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/discrete/tests/CMakeLists.txt;0;")
add_test(testSerializationDiscrete "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/discrete/tests/testSerializationDiscrete")
set_tests_properties(testSerializationDiscrete PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/discrete/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/discrete/tests/CMakeLists.txt;0;")
add_test(testSignature "/home/leah/catkin_ws/build_isolated/gtsam/install/gtsam/discrete/tests/testSignature")
set_tests_properties(testSignature PROPERTIES  _BACKTRACE_TRIPLES "/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;176;add_test;/home/leah/catkin_ws/src/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/home/leah/catkin_ws/src/gtsam/gtsam/discrete/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/home/leah/catkin_ws/src/gtsam/gtsam/discrete/tests/CMakeLists.txt;0;")
